services:
  laravel-user-services:
    build: ./todo-list-app-laravel
    container_name: laravel-user-services
    ports:
      - 8000:8000
    networks:
      - first-microservice-network

  spring-task-services:
    build: ./todo-list-app-spring
    container_name: spring-task-services
    ports:
      - 8080:8080
    networks:
      - first-microservice-network
    depends_on:
      - laravel-user-services


  todo-list-front:
      build: ./todo-list-front
      image: todo-list-frontend:latest
      container_name: todo-list-frontend
      ports: 
      - 3000:3000
networks:
  first-microservice-network:
    driver: bridge
  