version: '3.8'

services:
  laravel-user-services:
    build: ./todo-list-app-laravel
    container_name: laravel-user-services
    ports:
      - 8000:8000
    networks:
      - first-microservice-network

  spring-task-services:
    build: ./todo-list-app-spring
    container_name: spring-task-services
    ports:
      - 8080:8080
    networks:
      - first-microservice-network
    depends_on:
      - laravel-user-services

networks:
  first-microservice-network:
    driver: bridge
